[workspace]
resolver = "2"
members = [
    "applications/esp32/hal/*",
    #"applications/esp32/idf/*",
    "drivers/*", 
    ]


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
