[workspace]
resolver = "2"
members = [
    "applications/esp32/hal/*",
    #"applications/esp32/idf/*",
    "drivers/*", "tools/wasm-compiler", 
    "wasm/dst_display_mod",
    "tools/wasm-compiler",
    ]


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
