[package]
name = "dst_display_mod"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true          #Link time opti
opt-level = "z"     #Super agressif > s
strip = true        #no debug symbols
codegen-units = 1   #opti